version: "3.8"

services:
  mongo:
    build: ./db
    hostname: mongo
    volumes:
      - ./data/db:/data/db
      - ./db/init:/docker-entrypoint-initdb.d/
    command: --bind_ip_all --replSet rs0 --keyFile /data/db.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: note
      MONGO_REPLICA_SET_NAME: rs0
    ports:
      - 27017:27017

  note:
    build: ./
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/admin-fe/node_modules
      - /usr/src/app/fe/node_modules
      - /usr/src/app/be/node_modules
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    environment:
      CORS_ORIGINS: http://localhost:3001,http://localhost:3002
      MONGO_DB_URL: mongodb://root:root@mongo:27017
      MONGO_DB_REPLICA: rs0
      STATIC_FOLDER: /usr/src/app/data/static
      FILE_TEMP_FOLDER: /usr/src/app/data/temp
      FILE_TEMP_DELETE_SCHEDULER: 0 0 0 * * 7
      FILE_TEMP_URL_PREFIX: /temp
      
