version: "3.8"

services:
  mongo:
    build: ./db
    hostname: mongo
    container_name: lote-mongo-1
    env_file:
      - .env
    volumes:
      - ./db/data:/data/db
      - ./db/init/init.sh:/scripts/init.sh
    command: --bind_ip_all --replSet rs0 --keyFile /data/db.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_REPLICA_SET_NAME: rs0
    ports:
      - 27017:27017

  note-be:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile.be
      args:
        - START_MODE=${START_MODE}
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./data-deploy/notes:/apps/fe/notes
      - ./data-deploy/today-i-learneds:/apps/fe/today-i-learneds
      - ./data-deploy/be/files:/apps/data/be-files
      - ./data-deploy/be/logs:/apps/be/logs
    environment:
      - BE_FILE_DIR=/apps/data/be-files
      - NOTES_PUBLISHED_DIR=/apps/fe/notes
      - TILS_PUBLISHED_DIR=/apps/fe/today-i-learneds

  note-fe:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile.fe
      args: # pass env to Dockefile because they are needed in build time
        - FE_DIR=/apps/fe
        - FE_DOMAIN=${FE_DOMAIN}
        - ADMIN_FE_DOMAIN=${ADMIN_FE_DOMAIN}
        - BE_DOMAIN=${BE_DOMAIN}
        - BE_API_URL=${BE_API_URL}
        - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
        - FE_NOTES_HTML_PATH=/${FE_PUBLISHED_NOTES_DIR}
        - FE_TILS_HTML_PATH=/${FE_PUBLISHED_TILS_DIR}
    depends_on:
      - note-be
    volumes:
      - ./data-deploy/notes:/apps/fe/notes
      - ./data-deploy/today-i-learneds:/apps/fe/today-i-learneds
      - ./data-deploy/fe/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
