version: "3.8"

services:
  mongo:
    image: mongo:latest
    restart: on-failure
    volumes:
      - ./data/db:/data/db
    command: --bind_ip_all --replSet rs0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: note
      MONGO_REPLICA_SET_NAME: rs0
    ports:
      - 27017:27017

  note:
    build: ./
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    environment:
      CORS_ORIGINS: http://localhost:3001,http://localhost:3002
      MONGO_DB_URL: mongodb://root:root@mongo:27017
      MONGO_DB_REPLICA: rs0
      STATIC_FOLDER: /usr/src/app/static
