version: "3.8"

services:
  mongo:
    build: ./db
    hostname: mongo
    container_name: lote-mongo-1
    env_file:
      - .env
    volumes:
      - ./db/data:/data/db
      - ./db/init/init.sh:/scripts/init.sh
    command: --bind_ip_all --replSet rs0 --keyFile /data/db.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_REPLICA_SET_NAME: rs0
    ports:
      - 27017:27017

  note-be:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile.be
      args:
        - FE_DIR=/apps/fe
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./data-deploy/fe/dist:/apps/fe-deploy:rw
      - ./data-deploy/be/files:/apps/data/be-files
      - ./data-deploy/be/logs:/apps/be/logs
      - ./data-deploy/fe/published-notes:/apps/fe/notes
    environment:
      - BE_FILE_DIR=/apps/data/be-files
      - VITE_APP_API_URL=${BE_API_URL}
      - VITE_APP_RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - VITE_APP_DEPLOY_DIR=/apps/fe-deploy
      - VITE_APP_NOTE_DIR=/apps/fe/notes
      - VITE_APP_NOTE_IMG_DIR=/apps/fe/note-img

  note-fe:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile.fe
      args: # pass env to Dockefile because they are needed in build time
        - FE_DIR=/apps/fe
        - FE_DOMAIN=${FE_DOMAIN}
        - ADMIN_FE_DOMAIN=${ADMIN_FE_DOMAIN}
        - BE_DOMAIN=${BE_DOMAIN}
        - BE_API_URL=${BE_API_URL}
    depends_on:
      - note-be
    volumes:
      - ./data-deploy/fe/dist:/apps/fe:ro
      - ./data-deploy/fe/nginx:/etc/nginx/conf.d
      - ./data-deploy/fe1:/apps/fe
    ports:
      - 80:80
