export default {
  NOTES: 'NOTES',
  NOTE_CREATE: 'NOTE_CREATE',
  NOTE_UPDATE: 'NOTE_UPDATE',
  NOTE_COMMENTS: 'NOTE_COMMENTS',

  TODAY_I_LEARNEDS: 'TODAY_I_LEARNEDS',
  TODAY_I_LEARNED_CREATE: 'TODAY_I_LEARNED_CREATE',
  TODAY_I_LEARNED_UPDATE: 'TODAY_I_LEARNED_UPDATE',

  EMOJIS: 'EMOJIS',
  EMOJI_CREATE: 'EMOJI_CREATE',
  EMOJI_IMPORT: 'EMOJI_IMPORT',
  EMOJI_UPDATE: 'EMOJI_UPDATE',
}
